spring:
  jpa:
    open-in-view: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/brule
    username: postgres
    password: postgres